"""CycloneDX SBOM generation for the frozen sidecar (review P1-13).

The SBOM is what lets an operator (or a scanner) answer "exactly which
versions are in this appliance?" without diffing the repo at the tag.  These
tests pin the two things that would make the document worthless without a
failing check: it must parse the lock's format correctly, and it must never
silently drop a requirement it cannot understand.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))

import export_sbom  # noqa: E402

# A trimmed copy of `uv export --frozen --format requirements-txt` output:
# the root project, a plain pin, a marker pin, and a multi-hash pin.
_A = "a" * 64
_B = "b" * 64
_C = "c" * 64
_SAMPLE = f"""\
# This file was autogenerated by uv.
-e . \\
    # via
    #   -r pyproject.toml
fastapi==0.115.6 \\
    --hash=sha256:{_A}
    --hash=sha256:{_B}
colorama==0.4.6 ; sys_platform == 'win32' \\
    --hash=sha256:{_C}
"""


def test_parse_requirements_reads_the_uv_export_grammar() -> None:
    entries = export_sbom.parse_requirements(_SAMPLE)

    assert entries[0] == {
        "name": "mercure-gateway",
        "version": None,
        "hashes": [],
        "scope": None,
    }
    by_name = {e["name"]: e for e in entries}
    assert by_name["fastapi"]["version"] == "0.115.6"
    assert by_name["fastapi"]["hashes"] == [_A, _B]
    # The marker is recorded without the trailing line-continuation backslash.
    assert by_name["colorama"]["scope"] == "sys_platform == 'win32'"
    assert by_name["colorama"]["version"] == "0.4.6"


def test_an_unparsable_requirement_is_reported_not_dropped() -> None:
    """A line the parser cannot read must surface in the document."""
    entries = export_sbom.parse_requirements("-e .\nweird!thing\n")
    weird = [e for e in entries if e["name"].startswith("weird")]
    assert weird and weird[0]["scope"] == "unparsed: weird!thing"


def test_build_sbom_marks_the_root_as_the_application() -> None:
    entries = export_sbom.parse_requirements(_SAMPLE)
    bom = export_sbom.build_sbom(entries, source_version={"version": "1.1.0-rc3"})
    apps = [c for c in bom["components"] if c["type"] == "application"]
    assert len(apps) == 1
    assert apps[0]["name"] == "mercure-gateway"
    assert apps[0]["version"] == "1.1.0-rc3"
    assert apps[0]["purl"] == "pkg:pypi/mercure-gateway@1.1.0-rc3"
    # Markers become scope=optional + a property, never a silent omission.
    colorama = next(c for c in bom["components"] if c["name"] == "colorama")
    assert colorama["scope"] == "optional"
    assert colorama["properties"][0]["value"] == "sys_platform == 'win32'"


def test_the_document_is_valid_cyclonedx_15() -> None:
    bom = export_sbom.build_sbom(
        export_sbom.parse_requirements(_SAMPLE),
        source_version={"version": "1.1.0-rc3"},
    )
    assert bom["bomFormat"] == "CycloneDX"
    assert bom["specVersion"] == "1.5"
    assert bom["serialNumber"].startswith("urn:uuid:")
    assert bom["metadata"]["component"]["version"] == "1.1.0-rc3"


def test_the_serial_is_deterministic_for_the_same_component_set() -> None:
    """Two builds of the same release produce the same serial number."""
    entries = export_sbom.parse_requirements(_SAMPLE)
    one = export_sbom.build_sbom(entries, source_version={"version": "1.1.0"})
    two = export_sbom.build_sbom(entries, source_version={"version": "1.1.0"})
    assert one["serialNumber"] == two["serialNumber"]
    other = export_sbom.build_sbom(entries, source_version={"version": "1.2.0"})
    assert other["serialNumber"] != one["serialNumber"]


@pytest.mark.skipif(shutil.which("uv") is None, reason="uv not on PATH")
def test_main_writes_an_sbom_from_the_committed_lock(tmp_path: Path) -> None:
    """End to end against the real lockfile the sidecar is frozen from."""
    out = tmp_path / "sbom.json"
    code = export_sbom.main(["--output", str(out)])
    assert code == 0
    bom = json.loads(out.read_text(encoding="utf-8"))
    assert len(bom["components"]) > 1
    # Every shipped component carries its lock digest, or a reason it cannot.
    for component in bom["components"]:
        if component["type"] == "library":
            assert component.get("hashes") or component.get("properties"), (
                f"{component['name']} has neither digest nor marker"
            )
